### ISSUE TITLE
Plugin activation error in Multisite

### ISSUE THREAD

**Issue by pradeep910** [rtCamp/embed-google-drive#11]
I tried installing this plugin in my Multisite environment. It threw this error.

```
[09-Mar-2022 06:45:03] WARNING: [pool www] child 13138 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Call to a member function using_index_permalinks() on null in /var/www/htdocs/wp-includes/rest-api.php:435"
[09-Mar-2022 06:45:03] WARNING: [pool www] child 13138 said into stderr: "Stack trace:"
[09-Mar-2022 06:45:03] WARNING: [pool www] child 13138 said into stderr: "#0 /var/www/htdocs/wp-content/plugins/embed-google-drive/includes/classes/class-rtcamp-google-embeds.php(71): get_rest_url(NULL, '/rt-google-embe...')"
[09-Mar-2022 06:45:03] WARNING: [pool www] child 13138 said into stderr: "#1 /var/www/htdocs/wp-includes/class-wp-hook.php(307): RT_Google_Embeds\rtCamp_Google_Embeds->oembed_providers(Array)"
[09-Mar-2022 06:45:03] WARNING: [pool www] child 13138 said into stderr: "#2 /var/www/htdocs/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)"
[09-Mar-2022 06:45:03] WARNING: [pool www] child 13138 said into stderr: "#3 /var/www/htdocs/wp-includes/class-wp-oembed.php(214): apply_filters('oembed_provider...', Array)"
[09-Mar-2022 06:45:03] WARNING: [pool www] child 13138 said into stderr: "#4 /var/www/htdocs/wp-includes/embed.php(130): WP_oEmbed->__construct()"
[09-Mar-2022 06:45:03] WARNING: [pool www] child 13138 said into stderr: "#5 /var/www/htdocs/wp-includes/embed.php(149): _wp_oembed_get_object()"
[09-Mar-2022 06:45:03] WARNING: [pool www] child 13138 said into stderr: "#6 /var/www/htdocs/wp-content/plugins/jetpack/modules/shortcodes/others.php(12): wp_oembed_add_provider('https://me.sh/*', 'https://me.sh/o...')"
[09-Mar-2022 06:45:03] WARNING: [pool www] child 13138 said into stderr: "#7 /var/www/htdocs/wp-content/plugins/jetpack/modules/module-extras.php(74): require_once('/var/www/htd..."
```

**Comment by pdclark** [comment]
Is there anything particular about this multisite's permalink structure — or perhaps have permalink not been set? 
I didn't get this error on a multisite here.

`rest-api.php:435` reads:

```php
if ( is_multisite() && get_blog_option( $blog_id, 'permalink_structure' ) || get_option( 'permalink_structure' ) ) {
		global $wp_rewrite;

		if ( $wp_rewrite->using_index_permalinks() ) {
			$url = get_home_url( $blog_id, $wp_rewrite->index . '/' . rest_get_url_prefix(), $scheme );
```

So for some reason core is finding `$wp_rewrite` as `null`...

The lines in the plugin don't do much...

```php
// Register custom oembed provider for google drive urls.
		add_filter( 'oembed_providers', array( $this, 'oembed_providers' ) );
	}

	/**
	 * Register custom oembed provider for google drive urls.
	 * 
	 * @param array $providers Default providers.
	 * 
	 * @return array Modified providers.
	 */
	public function oembed_providers( $providers ) {
		$formats = array(
			'#https?:\\/\\/docs\\.google\\.com\\/document\\/d\\/(.*)\\/(.*)?#i',
			'#https?:\\/\\/docs\\.google\\.com\\/forms\\/d\\/(.*)\\/(.*)?#i',
			'#https?:\\/\\/docs\\.google\\.com\\/spreadsheets\\/d\\/(.*)\\/(.*)?#i',
			'#https?:\\/\\/docs\\.google\\.com\\/presentation\\/d\\/(.*)\\/(.*)?#i',
			'#https?:\\/\\/drive\\.google\\.com\\/open\\?id\\=(.*)?#i',
			'#https?:\\/\\/drive\\.google\\.com\\/file\\/d\\/(.*)\\/(.*)?#i',
			'#https?:\\/\\/docs\\.google\\.com\\/drawings\\/d\\/(.*)\\/(.*)?#i',
		);
		
		foreach ( $formats as $format ) {
			$providers[ $format ] = array( get_rest_url( null, 'rt-google-embed/v1/oembed' ), true );
		}
```

And the `null` being passed to `get_rest_url()` doesn't seem to the the `null` causing the error... :/

/cc @rutviksavsani

**Comment by pradeep910** [comment]
@pdclark I tested on default %postname% permalink and subdomain setup. When I tried to activate it network wide, it threw error. I do have a lot of plugins though like, newspack plugins, jetpack, sitekit, etc. but that should not create any problem I think. I will see if I can get more info.

**Comment by pradeep910** [comment]
@pdclark So I tested and found that it is not working with jetpack. Please check for jetpack compatibility.
